import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const roboto = localFont({
  src: [
    {
      path: '../fonts/Roboto-VariableFont_wdth,wght.ttf',
      weight: '100 900',
      style: 'normal',
    },
    {
      path: '../fonts/Roboto-Italic-VariableFont_wdth,wght.ttf',
      weight: '100 900',
      style: 'italic',
    },
  ],
  variable: '--font-roboto',
});

const titanOne = localFont({
  src: '../fonts/TitanOne-Regular.ttf',
  weight: '400',
  style: 'normal',
  variable: '--font-titan',
});

const opsOne = localFont({
  src: '../fonts/BlackOpsOne-Regular.ttf',
  weight: '400',
  style: 'normal',
  variable: '--font-ops',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${titanOne.variable} ${opsOne.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
